#!/bin/bash
# Lancer un shell depuis un container alpine, en faisant en sorte que vous puissiez
# directement interagir avec le container via votre terminal et que le container se
# supprime à la fin de l’exécution du shell.
docker run --rm -it alpine /bin/sh