#!/bin/bash
# Lancer un container mysql en tâche de fond. Il devra aussi pouvoir redémarrer de
# lui-même en cas d’erreur et faire en sorte que le mot de passe root de la base de
# données soit Kerrigan. Vous ferez aussi en sorte que la base de données soit stockée
# dans le volume hatchery, que le container crée directement une base de données
# qui aura comme nom zerglings et le container s’appellera spawning-pool.
docker run  --detach --restart=on-failure \
	--name spawning-pool --env="MYSQL_ROOT_PASSWORD=Kerrigan" \
	--env="MYSQL_DATABASE=zerglings" \
	-v hatchery:/var/spool/mysql mysql