#!/bin/bash
# Démarrer un container qui se nommera Abathur. Abathur sera un container Python
# en version 2-slim, qui aura son dossier /root bindé à un dossier du HOME de votre
# host, ainsi que le port 3000 bindé au port 3000 de votre machine virtuelle.
# Vous personnaliserez ce container de telle sorte que vous puissiez utiliser le microframework
# Flask dans sa dernière version. Vous devrez faire en sorte qu’une page
# html renvoyant un "Hello World" dans des balises <h1>, soit servie par Flask.
# Vous testerez la bonne mise en place de votre container, en accédant via curl ou
# navigateur web,à l’adresse IP de votre machine virtuelle sur le port 3000.
# Vous listerez aussi toutes les commandes nécessaires dans votre rendu.
# mkdir -p ~/root
docker run -it --name Abathur -v ~/root:/root -p 3000:3000 python:2-slim bash
# dans le container (réponse demandée)
# pip install Flask
# apt-get update
# apt-get install -y vim
# dans vim
# créer app.py dans ~/root
# from flask import Flask
# app = Flask(__name__)
# @app.route('/')
# def index():
#     return ('<!DOCTYPE html><html><head><title></title></head><body><h1>Hello World</h1></body></html>')

# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port="3000")

# # puis lancer
# python /root/app.py