#!/bin/bash
# Lancer un SERVICE rabbitmq qui aura pour nom orbital-command. Vous devrez
# définir un user et un mot de passe spécifiques à l’utilisation du service RabbitMQ,
# et ceux-ci seront à votre libre convenance. Ce service sera sur le reseau overmind
docker service create --name orbital-command --network overmind \
 	-e RABBITMQ_DEFAULT_USER=rabbit -e RABBITMQ_DEFAULT_PASS=rabbit rabbitmq