#!/bin/bash
# Récuperer les logs en continu d’une des tasks du service engineering-bay
# les 2 commandes ci-dessous ne marche qu'avec Docker en mode expérimental
# docker-machine ssh Char
# docker service logs --follow engineering-bay
# ou sinon, puisque le premier ne marche pas
# on récupère le nom exact du service avec
docker ps
# et on utilise docker logs --follow nom_du_service
docker logs --follow $(docker ps | grep engineering-bay | awk '{print $1}')