#!/bin/bash
# ... Damn, des zergs sont en train d’attaquer orbital-command et couper le service
# engineering-bay ne servira a rien... Vous devez envoyer des Marines pour les
# éliminer... Lancer un service 42school/marine-squad en 2 repliques, et faites en
# sorte que le service fonctionne (se référer à la doc fournie dans hub.docker.com).
# Ce service s’appellera ... marines et sera sur le reseau overmind
docker service create --name marines --network overmind \
 	 --replicas 2 -e OC_USERNAME=rabbit -e OC_PASSWD=rabbit 42school/marine-squad